### ISSUE TITLE
對於Lizzie v0.5+的期待與建議

### ISSUE THREAD

**Issue by atoutw** [zsalch/lizzie#1]
@zsalch 
首先感謝您對Lizzie程式的無私貢獻！

以下是我非常期盼v0.5+能增加的功能，但對於此程式增加這些功能的難易度實在不懂，請作為參考就好，謝謝。

1. 附解說的節點上使用不同顏色（參考Sabaki）
2. 可直接在解說窗口內輸入文字
3. 新增跳往前/下一解說的快捷鍵（參考Sabaki的Ctrl+Shift+Up Arrow）
4. 新增返回父分支的快捷鍵（參考Sabaki的Ctrl+Left Arrow）
5. 新增形勢判斷功能（參考Sabaki的Estimate功能鍵或使用Zen7）
6. 除了AQ，再增加Zen7引擎（理由：① Zen7附有參考性高的形勢判斷功能　②Zen7可任意調整貼目　③Zen7對於征子棋形極為敏銳，剛好可補足LZ和ELF的不足）
7. 銜接6，增加棋局中可隨意調整貼目的功能

※翻譯成英文需要一點時間，不確定能否在今日同步於featurecat/lizzie。

**Comment by zsalch** [comment]
都是非常实用的建议。
1、3、4：是比较容易实现的；
2：则有点麻烦；
5：其实现在Lizzie也有这个功能，不过似乎只在终局时可用，而且不太准确。未来可考虑调用外部程序实现，比如Zen、GnuGo等等；
6：增加引擎需要很多工作量，我想短时间我们可能看不到这个功能；
7：任意贴目应该更加困难，目前AI的基本基于Alpha Zero论文通过自我训练进化，都是固定7.5贴目，所以贴目不能随意更改。不过，也有不少人致力于这个工作，我们可以关注他们的进展以及Leela的更新。

另：pre-release刚刚更新过，解决了之前提到的一些问题，希望能有些帮助。

**Comment by atoutw** [comment]
![image](https://user-images.githubusercontent.com/43053753/45396916-ae377180-b678-11e8-9f6a-10206a647a1d.png)
解說窗口的儲存勝率，不知道能不能做以下調整：
(172948)(63.52%)　→　（ELFv0／172k）63.5%
①新增儲存時評價勝率所用的AI引擎。
②172948位數太多，建議超過1000後用k表示。
③63.5%比63.52%更容易讀。
④勝率應該不需加（）。

**Comment by atoutw** [comment]
@zsalch 
關於解說窗口的勝率表示，希望能再加上和前一手比較的勝率變化（即Lizzie勝率變化圖上的Last move: +/-n%的部分），表示法建議如下範例：

（ELFv0／172k）63.5%（-0.3%）

另外想到一點，希望使用者能自行設定一個值（例如5或10），當一手棋勝率下降超過該值時，節點就變紅色，提醒使用者這步可能是壞棋。

**Comment by zsalch** [comment]
这个也在我的考虑之内，如果有时间会很快实现这个功能。

增加引擎需要修改现有程序结构，工作量较多，同时对现有程序影响也比较大。即使实现，短时间应该也不会合并到官方版本，这需要时间验证来得到开发者的承认。

**Comment by atoutw** [comment]
真的非常地感謝你！

又想到了幾個希望能增加的功能，在用英文整理好完整版建議前，想先請您看看。
１、儲存過的勝率，在下次用Lizzie開啟時也能顯示winrate display的勝率變化曲線。
２、variation graph的節點，可以直接點擊該節點讓棋譜跳至該手棋的位置。（參考Sabaki）
３、自訂N值，顯示「最後N手」的手數。（參考MultiGo）或自訂顯示第A手到第B手的手數。
４、自訂背景圖。

**Comment by zsalch** [comment]
1. 大概您是想将存储的胜率变化曲线用不同的颜色显示出来，和当前使用的引擎对比？
2. 这个功能由于目前程序特点实现起来会有些困难
3. 这个显示手数您是指棋上的数字？因为我很少使用MultiGo，也许涉及它的功能可能需要您稍作详细地说明
4. 这个目前其实Lizzie是支持Theme的设置，但是有点麻烦，需要一定的编程知识，也许我可以做一个折中的方案，可以直接使用图像文件可能方便更改些

**Comment by atoutw** [comment]
@zsalch 
1、我是希望儲存的勝率，在下次用Lizzie開啟時能繼續顯示為當前的勝率變化曲線圖（並非兩個來對比），就像儲存前一樣。目前開啟時winrate display是空白的。
![180917_tempsnip](https://user-images.githubusercontent.com/43053753/45610747-ffd86580-ba97-11e8-9424-1dfd37b6a683.png)
2、了解，謝謝。
3、是的，顯示手數是指棋子上的数字。（例：如下圖，是用MultiGo顯示「最後20手」）
![image](https://user-images.githubusercontent.com/43053753/45610427-d703a080-ba96-11e8-9c78-080c2d2be301.png)
4、謝謝。非常期待！

**Comment by zsalch** [comment]
1. 了解
2. 对于节点的修改，可能需要做一些比较大的变更，所以所有相关节点的操作，会延后进行
3. 了解，这个应该会很快实现
4.  这个已经实现，我昨天更新了pre-release，并且创建了一个新的Issue（#361），具体使用说明可以参考里面的内容

PS： pre-release会不定期的更新，每次更新不一定会写在Issue中，不过pre-release里面会标一下更新的日期。

**Comment by atoutw** [comment]
@zsalch 
已經試用了Lizzie-v0.5+（Sep 18版），新的Custom Theme真的非常漂亮！不過還是有一點小小問題和新的建議如下：

１、使用新Theme後，擺棋譜越到後面感覺棋子越「重」，我把棋子的file換成以前的就改善了，不知這個問題是否能調整？
２、'only-last-move-number'功能，不知是否能改為直接在程式中使用（例如現行的"a"功能鍵）。希望能設一個功能鍵，按了後可自訂從Ａ手到Ｂ手的顯示手數。
３、Comment欄內的文字太多時會看不到，是否能改成捲動視窗？另外，建議把Comment欄的大小固定，或放在variation graph的上方，目前版本Comment欄依文字數改變大小，文字跳來跳去會影響閱讀。
４、感謝您這麼快就採納儲存勝率的建議，試用後有的新的想法，如下例：
原來
(ELFv0/15k)37.4%(-6.2%)
改為
37.4% (Last move: -6.2%)
(ELFv0/15k playouts)
ps."("前和":"後希望加空格。

不好意思沒有附說明圖，不知這些建議容易了解嗎？如果有問題我會個別加圖檔詳細說明。真的非常謝謝您！

**Comment by zsalch** [comment]
我更新了pre-release，改善了显示棋子的性能，还请重新下载试用，看看是否有改善。
关于commnet的显示，会考虑改善，现在如果显示不下，可以关掉Variation Tree，comment会显示更多内容。

**Comment by zsalch** [comment]
关于胜率的保存，由于可能会显得比较乱，所以不被官方认可，现在默认是关闭的。
可以在config.txt中增加"append-winrate-to-comment": true,来打开。

**Comment by atoutw** [comment]
@zsalch 
試用Sep.20版後，棋子變重的問題已經完全解決，太感謝了！

關於勝率的保存，如果不會占用太多時間的話，還是希望能將現在的勝率顯示格式改為如照片顯示的格式，比較整齊易讀。其實我認為對於用Lizzie復盤檢討或布局研究的棋手，最希望保存的除了變化圖，就是每一手的勝率了，很希望未來官方能認可。

**Comment by atoutw** [comment]
@zsalch 
Lizzie-v0.5+程式問題與新的建議：

１、Lizzie-v0.5+偶爾會出現搜尋整個棋盤導致整盤都是選點的情形（圖１），同樣的局面在官方0.5版，勝率是被消掉的（圖２），不知能否做跟官方一樣的修改？如果可能，希望進而能設定同一局面的顯示選點最多10個、15個或20個，或者在config.txt中能讓使用者自訂。

<img width="790" alt="180922_lizzie v0 5 _bug03" src="https://user-images.githubusercontent.com/43053753/45914815-51606600-be85-11e8-9a9b-d039dea47744.PNG">（圖１）

<img width="788" alt="180922_lizzie v0 5 _bug02" src="https://user-images.githubusercontent.com/43053753/45914820-65a46300-be85-11e8-955b-627de33dd69d.PNG">（圖２）

２、希望顯示sgf檔所保存的符號（圖３）。

<img width="500" alt="180922_lizzie v0 5 _bug04" src="https://user-images.githubusercontent.com/43053753/45914830-87054f00-be85-11e8-80b7-486ca797469b.PNG">（圖３）

３、目前"a"快捷鍵只能設定分析一手棋多少playouts，希望增加分析一手多少秒的選項，如此可以固定速度方便看棋。

４、希望新增讓AI自動下棋功能，目前只能按"Enter"強迫AI下一手，希望多一個快捷鍵（例如Ctrl+p），讓AI持續下下去，直到再按一次快捷鍵才停止。

５、承４，希望能在按下４中所述"Ctrl+p"快捷鍵後，出現一個新視窗，讓使用者設定黑棋和白棋的執行AI，並能設定一手棋多少playouts或一手多少秒。

６、目前正在思考一個類似「絕藝檢討」或「弈客鹰眼」的簡易版分析棋譜功能。相信Lizzie能保存每一手的勝率和（和前一手的）勝率差的話，不難在分析完最後一手後，自動匯出分析結果報告。我將做一個範例圖後貼上來請您參考，謝謝。

**Comment by zsalch** [comment]
关于问题1，其实没有对这一块进行修改，也许可以使用同一个config.txt试试，或者检查config.txt中的min-playout-ratio-for-stats值是否一致。

其它问题，我想问题2会在近期考虑范围内，其它的问题只能慢慢追加了。毕竟Lizzie的设计初衷是用来实时分析，本来可能的话，我还想有时间为Sabaki追加实时分析功能，再改下去，我想我不再需要Sabaki了。:)

**Comment by atoutw** [comment]
@zsalch 
更新2018-09-24版了！非常感謝您採納關於Comment和勝率格式的建議！
不過真的很不好意思，經過不斷試用及仔細思考後，覺得勝率格式還能改得更好，就是把"Black(White)"改成"Move 手數"（如下圖），如此不僅知道黑棋白棋，也能知道這是第幾手的勝率，另外視覺效果也會比較整齊。關於勝率格式一改再改真的抱歉，但非常希望您能採納此建議。
![180925_lizzie v0 5 01](https://user-images.githubusercontent.com/43053753/45963033-35172180-c05d-11e8-9e32-1fb04ffb3b52.png)

**Comment by ParmuzinAlexander** [comment]
lizzie-0.5.jar not work
For lizzie-0.5-shaded.jar
Path to leelaz ./leelaz not work, need .\\leelaz.exe, old config.txt?
Double shadow when showing next move.
custom-theme not work.
resume-previous-game not work or how to use it?
append-winrate-to-comment + autosave-interval-seconds copies a comment many times, 10s autosave  and after 50s - 5 comments for 1 move.

**Comment by zsalch** [comment]
@ParmuzinAlexander

>> Double shadow when showing next move.
I think I don't understand what you mean.

>> resume-previous-game not work or how to use it?
set the resume-previous-game to true, and the autosave has content in the persist file.

>> append-winrate-to-comment + autosave-interval-seconds copies a comment many times, 10s autosave and after 50s - 5 comments for 1 move.
I have not encountered this problem, what system are you? Windows?Linux?MacOS?

**Comment by atoutw** [comment]
@zsalch 

簡單整理2018-10-1版遇到的問題：
1、偶爾持續在pondering on狀態下跑了很久後，運算會突然停止，切換其他AI後又開始運算。
2、手動拉動視窗邊界調整視窗大小時，棋盤大小的反應非常慢，偶爾因此程式當住不動。
3、按「i」鍵輸入黑白名字後，無法立刻反應在視窗上方白邊的資訊上。
4、當前手數顯示在勝率線圖的下方，白色字體剛好被下方的白色部分擋住，難以識別。建議仿造sabaki的手數顯示法加上一個背景方塊，位置則維持現狀很好，不建議更改。

新的建議：
1、目前刪除棋子時，若不是最後一手，會把後面手數的棋子一併刪掉，希望增加只刪除當前手數的棋子的功能鍵（例如Ctrl+d）
2、以前有類似建議，希望增加一鍵從分支變化圖跳回主譜的功能鍵。
3、以前有類似建議，希望顯示全部手數的狀態下，在擺分支變化圖時，主譜手數能消掉，分支手數從1開始。
4、以前有類似建議，希望'only-last-move-number'功能，能改為直接在程式中用功能鍵啟動。

**Comment by zsalch** [comment]
我更新了Pre-release，其中config.txt及sabaki sample也更新了，可以参考。

Ctrl+Left: 跳转到主谱
Ctrl+Shift+Up/Donw: 跳转到带评论的节点
m: 在显示所有手数/最后手数/不显示手数之间切换。

**Comment by atoutw** [comment]
@zsalch 
關於2018-10-20版。
剛才試著更新Pre-release檔，並按照config.txt.sample更新，sabaki sample也下載後覆蓋原檔，但仍然打不開，錯誤訊息的畫面如下：
<img width="790" alt="181020_lizzie v0 5 _bug01" src="https://user-images.githubusercontent.com/43053753/47258409-b2577a00-d4d5-11e8-820e-cf4d83fb7e0f.PNG">

我的檔案放置方法如下：
<img width="266" alt="181020_lizzie v0 5 _bug02" src="https://user-images.githubusercontent.com/43053753/47258438-0e220300-d4d6-11e8-95ce-ff1e8984877d.PNG">
<img width="249" alt="181020_lizzie v0 5 _bug03" src="https://user-images.githubusercontent.com/43053753/47258440-111cf380-d4d6-11e8-8444-abc000b1c38b.PNG">
config.txt寫法如下：
[config.txt](https://github.com/zsalch/lizzie/files/2498371/config.txt)

如果不嫌麻煩的話，能否幫忙檢查問題出在哪裡。沒時間也沒關係，我會慢慢等詳細說明放出後再自行研究，謝謝。

**Comment by zsalch** [comment]
这是没有找到leelaz，如果是windows平台，./leelaz 应该改为 .\leelaz.exe 或者 直接用 leelaz.exe。

**Comment by atoutw** [comment]
@zsalch 

感謝回覆！已經能使用了！2018-10-20版的勝率曲線圖增加了勝率變化的直條圖，variation graph的節點也會隨著勝率變化改變顏色，而且好像可以自訂顏色，感覺這些改變都非常棒！！

不過馬上發現一個問題（還是我設定錯誤？），當擺分支變化圖時，主譜的勝率曲線會跑到棋盤中央（如下圖），請確認一下，謝謝。

![image](https://user-images.githubusercontent.com/43053753/47267646-c6f14c00-d581-11e8-941e-df7f2d908bb1.png)

**Comment by atoutw** [comment]
@zsalch 

新版本玩得有點欲罷不能（笑）自己改了一下配色如下圖：

![image](https://user-images.githubusercontent.com/43053753/47269325-10986180-d597-11e8-8e8c-d11e9274c5e3.png)
    "blunder-node-colors":
    [      [        255,        0,        0      ],      [        255,        75,        0      ],      [        255,        150,        0      ],              55,        225,        0      ],      [        150,        255,        0      ],      [        75,        255,        0      ]    ],
    "blunder-winrate-thresholds": [      -30,      -20,      -10.1,      -5.1,      5,      10.1    ],
  "winrate-line-color": [0, 255, 0],
  "winrate-miss-line-color": [135, 135, 135, 200],
  "blunder-bar-color": [199, 0, 50, 200]

另外，請問勝率曲線圖的大小可以恢復以前的大小嗎？或者可以自行更改嗎？（下圖為以前的勝率曲線圖大小）

![image](https://user-images.githubusercontent.com/43053753/47269364-a9c77800-d597-11e8-92dd-02b1aa3398e0.png)

**Comment by atoutw** [comment]
https://github.com/gcp/leela-zero/issues/1945

![image](https://user-images.githubusercontent.com/43053753/47348048-8f9eae80-d6eb-11e8-9acd-1f5a6d380509.png)

經測試ELFv1比舊版Leela Zero引擎快了2倍以上，請問有沒有可能套用在Lizzie上？

**Comment by ParmuzinAlexander** [comment]
@zsalch 
1 lizzie-0.5-shaded.jar win 8.1 x64 java (build 1.8.0_181-b13)
Normal shadow https://imgur.com/s8M5FTP
Double shadow https://imgur.com/SkLKHMR
2 I'm edited persist file, resume-previous-game work.
3 "autosave-interval-seconds": 10 +  "append-winrate-to-comment": true, copies a comment many times, 10s autosave and after 50s - 5 comments for 1 move. Also the background changes with visible scrolling https://imgur.com/mapqRFB

**Comment by zsalch** [comment]
@atoutw 
新版leelaz应该可以支持，请直接尝试使用。

**Comment by zsalch** [comment]
@ParmuzinAlexander 
I have fixed the double shadow issue.

**Comment by zsalch** [comment]
@atoutw 
运行时间长变慢的问题，建议可以直接到leelaz的issue下提问。
另外最近又修正了一些问题。

**Comment by atoutw** [comment]
@zsalch 

有職業棋士反應，能不能只看到自己的勝率顏色。基於此點，小弟想到一個新的節點表示法，黑白節點如下圖位置錯開，黑左白右，惡手是哪方下的一目了然。至於當前位置，感覺改用紅色外圈更為醒目。
![image](https://user-images.githubusercontent.com/43053753/47608531-15af5200-da6a-11e8-9ac2-30450a62bc2f.png)

至於分支，做了一個範例如下。
![image](https://user-images.githubusercontent.com/43053753/47608603-2b714700-da6b-11e8-994b-33add8979fbb.png)

另外，點擊功能很不錯，不過建議仿照sabaki的方式，鼠標滑過節點時節點放大，點擊後像sabaki的做法加一點延遲，讓當前位置的節點慢慢移至中央。

節點表示加延遲的做法似乎也可以用在普通走棋子時，如此比較看得出節點的動作。

諸多意見請參考，謝謝。

**Comment by zsalch** [comment]
这个issue的内容和经历的改变已经太多了，看起来有些混乱，让我们关闭它吧。
请将待解决或期望的问题分类拆开提交不同的issue，这样方便我们一个一个地去解决它们，谢谢。

**Comment by atoutw** [comment]
能否請教如何關閉這個issue？謝謝。
