### ISSUE TITLE
左右移动主棋盘，显示更大的winrate和variation

### ISSUE THREAD

**Issue by phiming** [zsalch/lizzie#10]
利用快捷键，比如“[", "]" 来左右移动主棋盘，以便显示更大的winrate，或者更多的variation
![1](https://user-images.githubusercontent.com/35087044/47917257-dd819680-dee3-11e8-9f57-442d86d97ab8.JPG)
![2](https://user-images.githubusercontent.com/35087044/47917276-f2f6c080-dee3-11e8-8f20-aef867449e34.JPG)
这样用户可以根据自己的需要把棋盘移动最佳位置，方便查看winrate或者分枝。
实现比较简单，能不能考虑加入这功能

**Comment by zsalch** [comment]
是个好想法，可以考虑。

**Comment by phiming** [comment]
lizzie本身不支持用户手动调窗口大小。这个小功能其实支持了手动调winrate或ariation窗口大小。因为很简单，我已做好了实现，会尽快提PR
