### ISSUE TITLE
关于replay branch

### ISSUE THREAD

**Issue by phiming** [zsalch/lizzie#12]
谢谢把这个功能提交给官方，让更多的人用上，我很开心。
官方提到的希望在replaying的时候不要关掉ponder，虽然可以简单的去掉两行代码，但有一定副作用。我有个更好点的想法，不暂停ponder，而是暂停实时更新到棋盘上。
现在我没法改代码，今晚我会提交改过的代码供参考

**Comment by zsalch** [comment]
这个功能很棒，我希望能有更多的人使用。
简单去除代码的确在回放时会被刷新掉，所以我reset了代码。
