### ISSUE TITLE
建议 增加修改棋子坐标的功能

### ISSUE THREAD

**Issue by ainixingo** [zsalch/lizzie#16]
![image](https://user-images.githubusercontent.com/40348917/48656132-c7cfad80-ea5b-11e8-912f-d14fac74f975.png)

先输入旧有手数或坐标
再输入新坐标/pass/swap(黑白替换) 這個功能好像Lizzie沒有？吧

**Comment by zsalch** [comment]
目前MyLizzie应该是单纯的替换，比如，如果Move 1 D16，Move 2 D4，那么更改1 为D4时，就直接替换掉Move 2，丢弃2。那么是是否意味着，还得增加为这个行为回退的功能，因为如果坐标输错，会引起更大的混乱。

同时swap功能也是强制更改颜色，如果连续的同色看起来会有些奇怪，也许插入些pass看起来更合理。

不过，也许程序不应该干涉这么多，仅提供功能，具体操作依赖于用户，这样实现会比较简单，太智能了，如果不符合用户预期，可能就变智障了。

**Comment by zsalch** [comment]
已经实现，使用Alt+M。
