### ISSUE TITLE
（建議）從搜索中排除指定座標

### ISSUE THREAD

**Issue by atoutw** [zsalch/lizzie#17]
@zsalch 

https://github.com/gcp/leela-zero/pull/1949
上面這個討論串，由於英文不好，看不太懂是否已經在LZ上實現，不過這是個非常好的想法，希望也能運用在Lizzie上。如此或許可以解決AI不會看征子等的問題。

例1：按Ctrl+A (avoid)，就可以打開一個功能視窗，然後輸入希望AI不搜索的座標，例如h11或h11, g11, g12(超過一個)

另外如果可能，也希望一起增加allow的功能，讓AI只去搜索使用者輸入進去的座標，如此可以針對特定座標進行勝率比較。或許在局部死活判斷時也非常有用。

例2：按Ctrl+A (avoid)，就可以打開一個功能視窗(如下圖)，然後選擇avoid或allow後，輸入座標。

![image](https://user-images.githubusercontent.com/43053753/48663819-e1630a80-ead8-11e8-85ca-b7a384c9be4f.png)

**Comment by zsalch** [comment]
非常好的功能，当这个PR被合并后，Lizzie会考虑跟进这个功能。

**Comment by zsalch** [comment]
已经实现。

**Comment by atoutw** [comment]
千等萬等的功能終於等到了，非常感謝！不過試用了一下，並無任何變化，請問是不是操作方法錯了？
（我設定avoid+black+Q12，希望黑能不搜索Q12，但是按下OK後，電腦還是搜索了Q12）

![lizzie_190321a](https://user-images.githubusercontent.com/43053753/54755371-2b93fe00-4c29-11e9-9c57-3df6da6fcc74.JPG)

另外，功能視窗在windows上好像無法全部顯示（如圖），望請修正。謝謝！
