### ISSUE TITLE
（建議）自動保存關閉程式前的設定

### ISSUE THREAD

**Issue by atoutw** [zsalch/lizzie#18]
@zsalch 

有一些設定，例如"C"的座標表示、"M"的手順編號、"[]"的主棋盤位置調整等，幾乎每次開啟程式時都要重新調整一次。請問能不能把關閉程式前的設定自動保存起來？或把自動保存設定功能的開啟與關閉加入config.txt？

**Comment by zsalch** [comment]
是个好建议，每次调整是挺烦。

**Comment by zsalch** [comment]
Fixed.
