### ISSUE TITLE
LeelaZero 0.17 doesn't play.

### ISSUE THREAD

**Issue by wonsiks** [zsalch/lizzie#19]
Thank you for your great work.
Your version is much better than lizzie original version.

After LZ 0.17 released when play against leelazero doesn't work.
LZ just start thinking but never play.

Could you check about this problem?

**Comment by zsalch** [comment]
I tested Leela Zero 0.17 and it looks fine.
Can you provide more details?

**Comment by wonsiks** [comment]
After start lizzie and AI begins pondering, I pressed 'n' to play against AI.
In the dialogue box I just pressed OK button and played my first move.
But AI doesn't think and doesn't play at all.

**Comment by zsalch** [comment]
Fixed play against 0.17.
