### ISSUE TITLE
bugfix: variation read/display issues

### ISSUE THREAD

**Issue by phiming** [zsalch/lizzie#2]
最近几天一直有用你为Lizzie加的新功能打谱，support sgf with variation and comments，非常好用，感谢！以后可以告别multigo了。

但也发现个bug， 附件是sgf文件，在multigo可以看到全部comments，但lizzie看不全。似乎是，对"["的处理出了bug。

还有个问题，在windows识别gbk编码的sfg文件出现乱码，但utf-8编码的文件正常。我不得不每次都用编辑软件把gbk编码转成utf-8，能不能加入自动识别棋谱的编码呢

还是中文用起来自在点：）
[Tictactoe-2.zip](https://github.com/zsalch/lizzie/files/2483291/Tictactoe-2.zip)

**Comment by zsalch** [comment]
这个bug我已经修正并提交了代码到next_dev，还没有pre-release.

关于编码的问题，我之前也考虑过，但是识别编码可能需要引入第三方库或做更多的工作。
也许在打开对话框中加编码列表也是个解决方案。但都需要时间调查，所以迟迟没有动手。

**Comment by zsalch** [comment]
？？

**Comment by zsalch** [comment]
？

**Comment by zsalch** [comment]
2

**Comment by phiming** [comment]
不是编码问题，我给的都是原始文件，我自己用的已手动转为utf-8。
![1](https://user-images.githubusercontent.com/35087044/47289657-5b18ed00-d62e-11e8-930d-d7514bc73620.JPG)
move number是15步，右边的连接显然不对。对照sabaki
![2](https://user-images.githubusercontent.com/35087044/47289699-93b8c680-d62e-11e8-9164-49f6ca2b6ef2.JPG)
此外，在如图节点，按右方向键跳分支时，lizzie当掉了没反应。再提供几个类似文件，都有问题。
[《林海峰名局细解2》.zip](https://github.com/zsalch/lizzie/files/2501104/2.zip)

建议跟sabaki对照比较，容易看出不同

**Comment by phiming** [comment]
关于编码，让程序自动识别确实比较难。奇怪的是sabaki似乎是做的挺好，不知道怎么做到的，是不是也采用了第三方库？ 另外，大部分棋谱应该不需要用户去设置编码，普通爱好者一般是打谱，而不用编辑棋谱

**Comment by phiming** [comment]
github抽风了吗，刚吞了我两个回复

**Comment by zsalch** [comment]
github刚恢复正常，挂了一天了。

我的sabaki只能识别gb2312，不能正常读取utf-8。

这几个sgf我调查一下。

**Comment by phiming** [comment]
那有点奇怪，我的sabaki确实能自动识别出两种编码。你用的是linux吗，我的os是win10中文版

**Comment by phiming** [comment]
刚在sabaki里发现这段，用了jschardet, 是Java script的自动识别编码
exports.parseFile = function(filename) {
    let iconv = require('iconv-lite')
    let jschardet = require('jschardet')
    let buffer = fs.readFileSync(filename)
    let encoding = 'utf8'
    let detected = jschardet.detect(buffer)
    if (detected.confidence > 0.2) encoding = detected.encoding
    content = iconv.decode(buffer, encoding)
    return exports.parse(content)
}

https://github.com/chardet/chardet
由python移植过来，不知道能不能变成java

**Comment by zsalch** [comment]
这几个sgf是很好的例子，我会尝试调整。

如果移植的话，可能还是找个现成的java库更快些。

**Comment by zsalch** [comment]
我修改了读取问题，并改善了分支显示。

**Comment by zsalch** [comment]
@phiming 
我尝试加了点击功能，欢迎批评指正。

**Comment by phiming** [comment]
很活跃啊（笑），lizzie的owner这么活跃就好了。 这个功能确实应该有，我会下载你的代码测试。有无考虑加上自动识别编码，这个功能蛮有用的

**Comment by phiming** [comment]
简单试用了下，点击没问题，工作的很好。但上次的棋谱的bug还在，下图是2-4.sgf
![3](https://user-images.githubusercontent.com/35087044/47570927-efa28880-d969-11e8-8b97-1025fc3ec78d.JPG)
左边的winrate窗口没有显示手数和胜率，似乎是新的bug。右边variation窗口仍然有错误的连接。
2-1.sgf的问题解决了

**Comment by zsalch** [comment]
提交了新修改，你的这个sgf真是巧，触发了分支与主干之间循环劫，让人很头疼如何解决。
不过正好有个issue在讨论这个问题，现在修改为简单地劫规则，所以问题也暂时没有了。

**Comment by zsalch** [comment]
@phiming 
不知道现在这个问题有没有改善？

**Comment by phiming** [comment]
暂时没发现新问题。
感谢新加的自动编码识别，再也没有讨厌的乱码了
