### ISSUE TITLE
support view some online go games?

### ISSUE THREAD

**Issue by wonsiks** [zsalch/lizzie#23]
I think this is a great idea.
However I can't find out where to connect.
When I try any url Lizzie shows invalid url message.
Could you give some sample or site url?

**Comment by zsalch** [comment]
Maybe you can get some url here:
https://home.yikeweiqi.com/#/live

**Comment by wonsiks** [comment]
@zsalch Thanks a lot...

**Comment by zsalch** [comment]
Support foxwq too.

**Comment by wonsiks** [comment]
@zsalch How can I get game URL from foxwq ?

**Comment by zsalch** [comment]
You share the game or url from the mobile client.

**Comment by zsalch** [comment]
@wonsiks 
You can try it:
https://home.yikeweiqi.com/#/live/room/19663/1/17642182
