### ISSUE TITLE
[Suggest] Open SGF file from internet URL

### ISSUE THREAD

**Issue by wonsiks** [zsalch/lizzie#24]
Current Lizzie can load SGF file only from local computer.
I thing it'll be better if Lizzie can load SGF from internet URL.
Multigo has that function.

Thank you.

**Comment by zsalch** [comment]
Could you give some url?
Or more information.

**Comment by wonsiks** [comment]
@zsalch In multigo software it's able to open sgf from internet url.
ex) [http://open.cyberoro.com/gibo/201907/ssfinal-hanyizhou.sgf](url)
![20190706_234112](https://user-images.githubusercontent.com/37356450/60757611-dfd65a80-a047-11e9-9405-236eddbacaba.png)

**Comment by zsalch** [comment]
It is now supported, except that the URL you provide does not appear to be a standard SGF file.

**Comment by wonsiks** [comment]
@zsalch Maybe it's because of the CHRACTER SET.
The URL which I've given contains Korean character set.

Thank you for your quick work. It's so cool~ :)

**Comment by zsalch** [comment]
KO[6.5], This should be KM[6.5].

(          ---------->  Compared to the standard sgf, there is one less here [;]
TE[2019 삼성화재배 통합예선결승]
RD[2019-07-05]
PC[한국기원]
TM[2시간]
LT[60]
LC[5]
KO[6.5]             ------------> KM[6.5]?
RE[182수 백불계승]
PB[박진솔]
BR[9단]
PW[한이저우]
HD[0]
WR[8단]

**Comment by wonsiks** [comment]
@zsalch Yes, they look like using KO instead of KM and RD instead of DT.

**Comment by zsalch** [comment]
The KO tag is a standard property:
Property:	KO
Propvalue:	none
Propertytype:	move
Function:	Execute a given move (B or W) even it's illegal. This is
		an optional property, SGF viewers themselves should execute
		ALL moves. It's purpose is to make it easier for other
		applications (e.g. computer-players) to deal with illegal
		moves. A KO property without a black or white move within
		the same node is illegal.

**Comment by wonsiks** [comment]
@zsalch So their using KO[6.5] is not seem to proper anyway.

**Comment by wonsiks** [comment]
@zsalch How can I open SGF directly from URL on Lizzie?
Any hotkey for it?

(Solved) Q key works. Thanks a lot...

**Comment by zsalch** [comment]
I released a new 0708.jar, you can try it.

It ignored the missing [;] and can open your url.

**Comment by wonsiks** [comment]
@zsalch I've checked it. It's so great!!
Now I don't need to save SGF file into my computer for review with Lizzie.
Lizzie can open it directly. So COOL~
Thanks.
