### ISSUE TITLE
Screen doesn't change immediately when switch engine.

### ISSUE THREAD

**Issue by wonsiks** [zsalch/lizzie#25]
I'm not sure but it seems that after total visit number exeeded then screen start to show changed winrates.
If I stayed long time before switch engine then I have to wait long time after switch to see new engine's suggestion even though the new engine was preloaded.

Check it please.
Thanks... :)

**Comment by zsalch** [comment]
You can try to turn off the 'Show Best Moves By Hold' in the Config dialog.

**Comment by wonsiks** [comment]
@zsalch Oh, yes it works. Thank you...
I was ignorant of it.... :)
