### ISSUE TITLE
Auto replay variation step by step

### ISSUE THREAD

**Issue by phiming** [zsalch/lizzie#3]
![41](https://user-images.githubusercontent.com/35087044/47603812-90a14a00-da23-11e8-8bf9-b8c225911149.gif)
鼠标置于某个best move时，通常会显示整个variation。按下R键（Replay），会一步步回放variation。我觉得这个idea还不错，做了个implementation，想并到你的next-dev分枝。
或许不用按R键，直接replay也是个考虑。
做的比较简单，还有些考虑不周，请指正。

**Comment by zsalch** [comment]
这个效果很棒，能合并到我的分支，那非常欢迎，只要新建个PR就可以了。
如果你同意，将来可以合并到官方版本中。

**Comment by phiming** [comment]
已提交PR，希望能有点用处。
官方owner不活跃，新版本迟迟不能推出。合到官方也不知道等到猴年马月（笑）
