### ISSUE TITLE
（建議）Variation Graph 樹狀節點的表示法

### ISSUE THREAD

**Issue by atoutw** [zsalch/lizzie#4]
@zsalch

有職業棋士反應，能不能只看到自己的勝率顏色。基於此點，小弟想到一個新的節點表示法，黑白節點如下圖位置錯開，黑左白右，惡手是哪方下的一目了然。至於當前位置，感覺改用紅色外圈更為醒目。
![image](https://user-images.githubusercontent.com/43053753/47608531-15af5200-da6a-11e8-9ac2-30450a62bc2f.png)
（問了幾位職棋，他們全數贊成這個改變！）

至於分支，做了一個範例如下。
![image](https://user-images.githubusercontent.com/43053753/47608603-2b714700-da6b-11e8-994b-33add8979fbb.png)

另外，點擊功能很不錯，不過建議仿照sabaki的方式，鼠標滑過節點時節點放大，點擊後像sabaki的做法加一點延遲，讓當前位置的節點慢慢移至中央。

節點表示加延遲的做法似乎也可以用在普通走棋子時，如此比較看得出節點的動作。

諸多意見請參考，謝謝。

_Originally posted by @atoutw in https://github.com/zsalch/lizzie/issues/1#issuecomment-433650399_

**Comment by zsalch** [comment]
很有想法，就是感觉有点奇怪。
鼠标滑过节点放大的效果考虑过，不过基于目前代码，需要更多运算，感觉并不是特别值得。也许以后表示方式改变后会考虑。
至于延迟效果，这可能看起来很好，但当前的优先级可能需要稍后，也许是0.7版本会考虑。

**Comment by atoutw** [comment]
@zsalch 

那麼另一個想法，也請參考看看。

如果設一個功能鍵（例如Ctrl+n），按下去可以讓黑棋節點縮小，顏色消掉（如下圖，畫得不好，請見諒）；再按一次則讓白棋節點縮小，顏色消掉（黑棋節點恢復）；按第三次則恢復原始狀態。如此一來，既可以實現只顯示單方的勝率變化，整體也不會變亂。

![image](https://user-images.githubusercontent.com/43053753/47689052-7b970780-dc2b-11e8-941e-4064a2a000b5.png)

**Comment by atoutw** [comment]
@zsalch 

![image](https://user-images.githubusercontent.com/43053753/47797978-c79c9600-dd6a-11e8-822a-1eb0be220537.png)
自己的idea這麼快就能被實現真的很開心！新功能對復盤太有用了！謝謝！

ps. 就是不明白為什麼是"Y"（笑）

**Comment by zsalch** [comment]
因为D已经被用了。:)
