### ISSUE TITLE
（BUG） 擺棋譜分支時，勝率曲線變形!

### ISSUE THREAD

**Issue by atoutw** [zsalch/lizzie#8]
![image](https://user-images.githubusercontent.com/43053753/47798529-e7808980-dd6b-11e8-9970-35548a3466ee.png)
如圖，10-30版在擺棋譜分支的時候，勝率會跳出100%，請確認。

**Comment by zsalch** [comment]
能否提供sgf文件，及详细些的操作步骤。

**Comment by atoutw** [comment]
@zsalch 

幾乎擺每盤職業棋譜都會碰到此問題。舉今天圍甲李世石對陳耀燁的棋做個例子。

![image](https://user-images.githubusercontent.com/43053753/47932494-d15dff00-df0c-11e8-9ba2-abf5c03d2a48.png)
黑21勝率約降了30%。

![image](https://user-images.githubusercontent.com/43053753/47932567-f8b4cc00-df0c-11e8-9f40-eeaf428cf21f.png)
改為AI的推薦手作為分支，原始勝率就跑掉了。

棋譜sgf文件如下連結：
http://kifudepot.net/kifucontents.php?id=suqTjxplkEPR0m2p71%2FoOQ%3D%3D

如此形況不勝枚舉。還需要更多例子的話，請告知。

**Comment by zsalch** [comment]
请使用1102版再尝试是否修正了这个问题。

**Comment by atoutw** [comment]
@zsalch 

1102版試用後，目前為止勝率曲線變形的問題沒有再發生，非常感謝！麻煩請關閉此issue。
