### ISSUE TITLE
（建議）棋譜分支手數的表示。

### ISSUE THREAD

**Issue by atoutw** [zsalch/lizzie#9]
![image](https://user-images.githubusercontent.com/43053753/47799404-8c4f9680-dd6d-11e8-9b30-24e0965aeab9.png)
如圖，10-30版若想要只顯示分支手數，必須先開config檔，把"only-last-move-number"改為分支所有手數的"7"，再重新開一次Lizzie，才能顯現分支的82-88手，實為不便，且最初手不易辨識。

![image](https://user-images.githubusercontent.com/43053753/47799694-231c5300-dd6e-11e8-8267-f54f4ac624bd.png)
此圖為MultiGo的表示法，從1開始，簡單易懂。

希望Lizzie的分支手數表示也能效法MultiGo，把分支當作一張新的棋譜，從1開始計數，"M"功能鍵在分支時，功能也不需改變，仍為如下順序：

Off -> 顯示所有分支手數 -> 顯示config設定的分支最後手數 -> Off

**Comment by zsalch** [comment]
最近对显示手数的逻辑进行了调整，您这个建议已经成为可能，应该很快就能看到，也许可以考虑使用Ctrl+M，来切换分支的手数显示方式。

**Comment by zsalch** [comment]
可以使用最新的发布试试，实时切换有点难度，暂时没有。

**Comment by atoutw** [comment]
@zsalch 

![image](https://user-images.githubusercontent.com/43053753/47954830-0b410b00-dfca-11e8-8d8f-51c34ea6723e.png)
試用後1102版，分支手數已經改變為從1開始計數，但發現一個新的問題。

![image](https://user-images.githubusercontent.com/43053753/47954850-6541d080-dfca-11e8-87b9-2dcfab8ebacb.png)
如圖，使用"Shift+左"把剛才的分支改為主支時，手數沒有繼續主支的手數，而是仍然從1開始。請確認，謝謝。

**Comment by zsalch** [comment]
更新了1103版

**Comment by atoutw** [comment]
@zsalch 
問題已解決，非常感謝！麻煩請關閉此issue。
